---
- name: check if exist apache
  command: service httpd status
  ignore_errors: True
  register: check_apache

# Apacheのインストール
- include: install.yml
  when: check_apache|failed

- name: enable apache
  service: name=httpd enabled=yes

- include: config.yml

- name: deploy config
  template: src=httpd.conf.j2 dest=/usr/local/apache2/conf/httpd.conf

- name: restart apache
  service: name=httpd state=restarted
